package src.vista;

import java.io.File;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.SpinnerNumberModel;
import static src.controlador.FlotillaBusesControlador.botonOperadorVolver;
import src.controlador.FlotillaBusesControlador;

public class ModuloFlotillaBuses extends javax.swing.JFrame {

    /**
     * Creates new form ModuloFlotillaBuses
     */
    public ModuloFlotillaBuses() {
        initComponents();
        setLocationRelativeTo(null);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        export_data = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        import_data = new javax.swing.JButton();
        CRUD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        placa_bus = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        color_bus = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        toggle_tipo = new javax.swing.JComboBox<>();
        toggle_estado = new javax.swing.JComboBox<>();
        spiner_capacidad = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Acciones = new javax.swing.JPanel();
        guardar_bus = new javax.swing.JButton();
        listar_bus = new javax.swing.JButton();
        editar_bus = new javax.swing.JButton();
        confirmar_edicion_bus = new javax.swing.JButton();
        eliminar_bus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        export_data.setBackground(new java.awt.Color(51, 204, 0));
        export_data.setText("Exportar Data");
        export_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                export_dataActionPerformed(evt);
            }
        });

        Volver.setBackground(new java.awt.Color(255, 0, 0));
        Volver.setText("VOLVER");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });

        import_data.setBackground(new java.awt.Color(255, 255, 0));
        import_data.setText("Importar Data");
        import_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                import_dataActionPerformed(evt);
            }
        });

        CRUD.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos"));

        jLabel1.setText("Capacidad:");

        jLabel2.setText("Placa:");

        jLabel3.setText("Tipo:");

        placa_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                placa_busActionPerformed(evt);
            }
        });

        jLabel4.setText("Estado:");

        jLabel5.setText("Color:");

        toggle_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Microbus", "County", "Pullman" }));
        toggle_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggle_tipoActionPerformed(evt);
            }
        });

        toggle_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Disponible", "No Disponible" }));

        spiner_capacidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spiner_capacidadStateChanged(evt);
            }
        });

        javax.swing.GroupLayout CRUDLayout = new javax.swing.GroupLayout(CRUD);
        CRUD.setLayout(CRUDLayout);
        CRUDLayout.setHorizontalGroup(
            CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CRUDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CRUDLayout.createSequentialGroup()
                        .addGroup(CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(placa_bus)
                            .addComponent(toggle_tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(CRUDLayout.createSequentialGroup()
                        .addGroup(CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(color_bus)
                            .addComponent(toggle_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spiner_capacidad))))
                .addContainerGap())
        );
        CRUDLayout.setVerticalGroup(
            CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CRUDLayout.createSequentialGroup()
                .addGroup(CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(placa_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CRUDLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(toggle_tipo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CRUDLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(spiner_capacidad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(color_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CRUDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toggle_estado, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Placa", "Tipo", "Capacidad", "Color", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Acciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Acciones"));

        guardar_bus.setText("Guardar");
        guardar_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardar_busActionPerformed(evt);
            }
        });

        listar_bus.setText("Listar");
        listar_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listar_busActionPerformed(evt);
            }
        });

        editar_bus.setText("Seleccionar");
        editar_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_busActionPerformed(evt);
            }
        });

        confirmar_edicion_bus.setText("Editar");
        confirmar_edicion_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmar_edicion_busActionPerformed(evt);
            }
        });

        eliminar_bus.setText("Eliminar");
        eliminar_bus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_busActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccionesLayout = new javax.swing.GroupLayout(Acciones);
        Acciones.setLayout(AccionesLayout);
        AccionesLayout.setHorizontalGroup(
            AccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(guardar_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listar_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editar_bus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(confirmar_edicion_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eliminar_bus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AccionesLayout.setVerticalGroup(
            AccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(AccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardar_bus, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(listar_bus, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(editar_bus, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(eliminar_bus, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(confirmar_edicion_bus, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CRUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(export_data, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(import_data, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Acciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Volver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(export_data, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(import_data, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(CRUD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(Acciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void export_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_export_dataActionPerformed
        // TODO add your handling code here:
        FlotillaBusesControlador buses = new FlotillaBusesControlador();
        buses.imprimirPdf();
    }//GEN-LAST:event_export_dataActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
        // TODO add your handling code here:
        botonOperadorVolver("admin");
    }//GEN-LAST:event_VolverActionPerformed

    private void import_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_import_dataActionPerformed
        // TODO add your handling code here:
        FlotillaBusesControlador buses = new FlotillaBusesControlador();
        JFileChooser seleccionarArchivo = new JFileChooser();
        int seleccionar = seleccionarArchivo.showOpenDialog(this);
        if (seleccionar == JFileChooser.APPROVE_OPTION){
            File archivo = seleccionarArchivo.getSelectedFile();
            try {
                buses.cargarCSV(archivo);
            } catch (SQLException ex) {
                Logger.getLogger(ModuloFlotillaBuses.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        buses.limpiarTabla(jTable1);
        buses.listarBuses(jTable1);
    }//GEN-LAST:event_import_dataActionPerformed

    private void placa_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_placa_busActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_placa_busActionPerformed

    private void guardar_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardar_busActionPerformed
        // TODO add your handling code here:
        FlotillaBusesControlador buses = new FlotillaBusesControlador();
        buses.agregar(placa_bus, toggle_tipo, spiner_capacidad, color_bus,toggle_estado,jTable1);
        buses.limpiarTabla(jTable1);
        buses.listarBuses(jTable1);
    }//GEN-LAST:event_guardar_busActionPerformed

    private void listar_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listar_busActionPerformed
        // TODO add your handling code here:
        FlotillaBusesControlador buses = new FlotillaBusesControlador();
        buses.limpiarTabla(jTable1);
        buses.listarBuses(jTable1);
    }//GEN-LAST:event_listar_busActionPerformed

    private void editar_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_busActionPerformed
        // TODO add your handling code here:
        FlotillaBusesControlador buses = new FlotillaBusesControlador();
        buses.editar(jTable1, placa_bus, toggle_tipo, spiner_capacidad, color_bus,toggle_estado);
    }//GEN-LAST:event_editar_busActionPerformed

    private void confirmar_edicion_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmar_edicion_busActionPerformed
        // TODO add your handling code here:
        FlotillaBusesControlador buses = new FlotillaBusesControlador();
        buses.actualizar(jTable1, placa_bus, toggle_tipo, spiner_capacidad, color_bus,toggle_estado);
        buses.limpiarTabla(jTable1);
        buses.listarBuses(jTable1);
    }//GEN-LAST:event_confirmar_edicion_busActionPerformed

    private void eliminar_busActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_busActionPerformed
        // TODO add your handling code here:
        FlotillaBusesControlador buses = new FlotillaBusesControlador();
        buses.eliminar(jTable1);
        buses.limpiarTabla(jTable1);
        buses.listarBuses(jTable1);
    }//GEN-LAST:event_eliminar_busActionPerformed

    private void toggle_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggle_tipoActionPerformed
        // TODO add your handling code here:
        if (toggle_tipo.getSelectedItem().equals("Microbus")){
            SpinnerNumberModel modelo = new SpinnerNumberModel(10,10,10,1);
            spiner_capacidad.setModel(modelo);
        }
        
        if (toggle_tipo.getSelectedItem().equals("County")){
            SpinnerNumberModel modelo = new SpinnerNumberModel(24,24,28,1);
            spiner_capacidad.setModel(modelo);
        }
        
        if (toggle_tipo.getSelectedItem().equals("Pullman")){
            SpinnerNumberModel modelo = new SpinnerNumberModel(45,45,45,1);
            spiner_capacidad.setModel(modelo);
        }
    }//GEN-LAST:event_toggle_tipoActionPerformed

    private void spiner_capacidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spiner_capacidadStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spiner_capacidadStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuloFlotillaBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuloFlotillaBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuloFlotillaBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuloFlotillaBuses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModuloPrincipal frame = new ModuloPrincipal();
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Acciones;
    private javax.swing.JPanel CRUD;
    private javax.swing.JButton Volver;
    private javax.swing.JTextField color_bus;
    private javax.swing.JButton confirmar_edicion_bus;
    private javax.swing.JButton editar_bus;
    private javax.swing.JButton eliminar_bus;
    private javax.swing.JButton export_data;
    private javax.swing.JButton guardar_bus;
    private javax.swing.JButton import_data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    private javax.swing.JButton listar_bus;
    private javax.swing.JTextField placa_bus;
    private javax.swing.JSpinner spiner_capacidad;
    private javax.swing.JComboBox<String> toggle_estado;
    private javax.swing.JComboBox<String> toggle_tipo;
    // End of variables declaration//GEN-END:variables
}
