# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7.41-debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306